from enum import Enum


class UserRole(str, Enum):
    ADMIN = "ADMIN"
    DEVELOPER = "DEVELOPER"
    CUSTOMER = "CUSTOMER"


class ProjectStatus(str, Enum):
    LEAD = "LEAD"
    NEW = "NEW"
    REQUIREMENTS_PENDING = "REQUIREMENTS_PENDING"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    BUILDING = "BUILDING"
    IN_PROGRESS = "IN_PROGRESS"
    DESIGN_REVIEW = "DESIGN_REVIEW"
    DEVELOPMENT = "DEVELOPMENT"
    CLIENT_REVIEW = "CLIENT_REVIEW"
    REVISION_REQUESTED = "REVISION_REQUESTED"
    APPROVED = "APPROVED"
    PAYMENT_PENDING = "PAYMENT_PENDING"
    DEPLOYING = "DEPLOYING"
    LIVE = "LIVE"
    COMPLETED = "COMPLETED"


class BuildStatus(str, Enum):
    QUEUED = "QUEUED"
    ANALYZING = "ANALYZING"
    GENERATING = "GENERATING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"


class BuildReviewStatus(str, Enum):
    PENDING_REVIEW = "PENDING_REVIEW"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class DeploymentStatus(str, Enum):
    NOT_READY = "NOT_READY"
    READY = "READY"
    QUEUED = "QUEUED"
    DEPLOYING = "DEPLOYING"
    DEPLOYED = "DEPLOYED"
    FAILED = "FAILED"
    ROLLED_BACK = "ROLLED_BACK"


class RevisionStatus(str, Enum):
    PENDING = "PENDING"
    IN_PROGRESS = "IN_PROGRESS"
    COMPLETED = "COMPLETED"
    REJECTED = "REJECTED"


class PaymentStatus(str, Enum):
    PENDING = "PENDING"
    PROCESSING = "PROCESSING"
    SUCCESS = "SUCCESS"
    FAILED = "FAILED"
    REFUNDED = "REFUNDED"


class PaymentType(str, Enum):
    ADVANCE = "ADVANCE"
    MILESTONE = "MILESTONE"
    FINAL = "FINAL"
    FULL = "FULL"


class FileCategory(str, Enum):
    LOGO = "LOGO"
    IMAGE = "IMAGE"
    DOCUMENT = "DOCUMENT"
    BRAND_ASSET = "BRAND_ASSET"
    REVISION_ATTACHMENT = "REVISION_ATTACHMENT"
    PREVIEW_SCREENSHOT = "PREVIEW_SCREENSHOT"


class InquiryStatus(str, Enum):
    NEW = "NEW"
    CONTACTED = "CONTACTED"
    QUALIFIED = "QUALIFIED"
    CONVERTED = "CONVERTED"
    CLOSED = "CLOSED"


class InquirySource(str, Enum):
    WHATSAPP = "WHATSAPP"
    CONTACT_FORM = "CONTACT_FORM"
    START_PROJECT_WIZARD = "START_PROJECT_WIZARD"
