"""create_initial_schema

Revision ID: d14eb2f45735
Revises: 
Create Date: 2026-09-28 21:40:51.565339

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = 'd14eb2f45735'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('portfolio_projects',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('technologies', sqlite.JSON(), nullable=False),
    sa.Column('thumbnail_url', sa.String(length=500), nullable=False),
    sa.Column('gallery_urls', sqlite.JSON(), nullable=False),
    sa.Column('live_demo_url', sa.String(length=500), nullable=True),
    sa.Column('results_summary', sa.String(length=255), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolio_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_projects_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolio_projects_slug'), ['slug'], unique=True)

    op.create_table('pricing_packages',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('price_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('features', sqlite.JSON(), nullable=False),
    sa.Column('delivery_days', sa.Integer(), nullable=False),
    sa.Column('revisions_included', sa.Integer(), nullable=False),
    sa.Column('is_popular', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pricing_packages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pricing_packages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pricing_packages_slug'), ['slug'], unique=True)

    op.create_table('services',
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('short_description', sa.String(length=500), nullable=False),
    sa.Column('full_description', sa.Text(), nullable=False),
    sa.Column('deliverables', sqlite.JSON(), nullable=False),
    sa.Column('icon_name', sa.String(length=100), nullable=False),
    sa.Column('starting_price_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_services_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_services_slug'), ['slug'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'DEVELOPER', 'CUSTOMER', name='user_role_enum', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)

    op.create_table('customers',
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=100), nullable=False),
    sa.Column('gstin', sa.String(length=50), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_user_id'), ['user_id'], unique=True)

    op.create_table('inquiries',
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('business_name', sa.String(length=255), nullable=True),
    sa.Column('business_type', sa.String(length=100), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('source', sa.Enum('WHATSAPP', 'CONTACT_FORM', 'START_PROJECT_WIZARD', name='inquiry_source_enum', native_enum=False), nullable=False),
    sa.Column('selected_package', sa.String(length=100), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'QUALIFIED', 'CONVERTED', 'CLOSED', name='inquiry_status_enum', native_enum=False), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inquiries_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_inquiries_status'), ['status'], unique=False)

    op.create_table('projects',
    sa.Column('project_number', sa.String(length=30), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('package_id', sa.String(length=36), nullable=True),
    sa.Column('inquiry_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('business_name', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('LEAD', 'NEW', 'REQUIREMENTS_PENDING', 'IN_PROGRESS', 'DESIGN_REVIEW', 'DEVELOPMENT', 'CLIENT_REVIEW', 'REVISION_REQUESTED', 'APPROVED', 'PAYMENT_PENDING', 'DEPLOYING', 'LIVE', 'COMPLETED', name='project_status_enum', native_enum=False), nullable=False),
    sa.Column('assigned_developer_id', sa.String(length=36), nullable=True),
    sa.Column('preview_url', sa.String(length=500), nullable=True),
    sa.Column('production_url', sa.String(length=500), nullable=True),
    sa.Column('custom_domain', sa.String(length=255), nullable=True),
    sa.Column('revisions_used', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['assigned_developer_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['inquiry_id'], ['inquiries.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['package_id'], ['pricing_packages.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_projects_assigned_developer_id'), ['assigned_developer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_projects_project_number'), ['project_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_projects_status'), ['status'], unique=False)

    op.create_table('payments',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('payment_type', sa.Enum('ADVANCE', 'MILESTONE', 'FINAL', 'FULL', name='payment_type_enum', native_enum=False), nullable=False),
    sa.Column('amount_inr', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'PROCESSING', 'SUCCESS', 'FAILED', 'REFUNDED', name='payment_status_enum', native_enum=False), nullable=False),
    sa.Column('razorpay_order_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_payment_id', sa.String(length=100), nullable=True),
    sa.Column('razorpay_signature', sa.String(length=255), nullable=True),
    sa.Column('invoice_number', sa.String(length=50), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invoice_number')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_razorpay_order_id'), ['razorpay_order_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_razorpay_payment_id'), ['razorpay_payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)

    op.create_table('project_activities',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('performed_by_user_id', sa.String(length=36), nullable=True),
    sa.Column('action_type', sa.String(length=100), nullable=False),
    sa.Column('old_status', sa.String(length=50), nullable=True),
    sa.Column('new_status', sa.String(length=50), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('is_visible_to_client', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['performed_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_activities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_activities_action_type'), ['action_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_activities_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_activities_project_id'), ['project_id'], unique=False)

    op.create_table('project_messages',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('sender_user_id', sa.String(length=36), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('is_internal_note', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_messages_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_messages_is_internal_note'), ['is_internal_note'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_messages_project_id'), ['project_id'], unique=False)

    op.create_table('project_requirements',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('business_summary', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.Text(), nullable=True),
    sa.Column('services_offered', sa.Text(), nullable=True),
    sa.Column('color_preferences', sa.String(length=255), nullable=True),
    sa.Column('reference_websites', sqlite.JSON(), nullable=False),
    sa.Column('social_links', sqlite.JSON(), nullable=False),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=50), nullable=True),
    sa.Column('physical_address', sa.Text(), nullable=True),
    sa.Column('special_requests', sa.Text(), nullable=True),
    sa.Column('is_submitted', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_requirements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_requirements_project_id'), ['project_id'], unique=True)

    op.create_table('revisions',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('requested_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'COMPLETED', 'REJECTED', name='revision_status_enum', native_enum=False), nullable=False),
    sa.Column('admin_response', sa.Text(), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_revisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revisions_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_revisions_status'), ['status'], unique=False)

    op.create_table('testimonials',
    sa.Column('client_name', sa.String(length=255), nullable=False),
    sa.Column('company', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('quote', sa.Text(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('project_id', sa.String(length=36), nullable=True),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_testimonials_id'), ['id'], unique=False)

    op.create_table('project_files',
    sa.Column('project_id', sa.String(length=36), nullable=False),
    sa.Column('revision_id', sa.String(length=36), nullable=True),
    sa.Column('file_category', sa.Enum('LOGO', 'IMAGE', 'DOCUMENT', 'BRAND_ASSET', 'REVISION_ATTACHMENT', 'PREVIEW_SCREENSHOT', name='file_category_enum', native_enum=False), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('stored_filename', sa.String(length=255), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_user_id', sa.String(length=36), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revision_id'], ['revisions.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_user_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_project_files_file_category'), ['file_category'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_files_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_files_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_project_files_revision_id'), ['revision_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_files_revision_id'))
        batch_op.drop_index(batch_op.f('ix_project_files_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_files_id'))
        batch_op.drop_index(batch_op.f('ix_project_files_file_category'))

    op.drop_table('project_files')
    with op.batch_alter_table('testimonials', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_testimonials_id'))

    op.drop_table('testimonials')
    with op.batch_alter_table('revisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_revisions_status'))
        batch_op.drop_index(batch_op.f('ix_revisions_project_id'))
        batch_op.drop_index(batch_op.f('ix_revisions_id'))

    op.drop_table('revisions')
    with op.batch_alter_table('project_requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_requirements_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_requirements_id'))

    op.drop_table('project_requirements')
    with op.batch_alter_table('project_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_messages_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_messages_is_internal_note'))
        batch_op.drop_index(batch_op.f('ix_project_messages_id'))

    op.drop_table('project_messages')
    with op.batch_alter_table('project_activities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_project_activities_project_id'))
        batch_op.drop_index(batch_op.f('ix_project_activities_id'))
        batch_op.drop_index(batch_op.f('ix_project_activities_action_type'))

    op.drop_table('project_activities')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_razorpay_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_razorpay_order_id'))
        batch_op.drop_index(batch_op.f('ix_payments_project_id'))
        batch_op.drop_index(batch_op.f('ix_payments_id'))
        batch_op.drop_index(batch_op.f('ix_payments_customer_id'))

    op.drop_table('payments')
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_projects_status'))
        batch_op.drop_index(batch_op.f('ix_projects_project_number'))
        batch_op.drop_index(batch_op.f('ix_projects_id'))
        batch_op.drop_index(batch_op.f('ix_projects_customer_id'))
        batch_op.drop_index(batch_op.f('ix_projects_assigned_developer_id'))

    op.drop_table('projects')
    with op.batch_alter_table('inquiries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inquiries_status'))
        batch_op.drop_index(batch_op.f('ix_inquiries_phone'))
        batch_op.drop_index(batch_op.f('ix_inquiries_id'))
        batch_op.drop_index(batch_op.f('ix_inquiries_customer_id'))

    op.drop_table('inquiries')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_user_id'))
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_id'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))

    op.drop_table('customers')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('services', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_services_slug'))
        batch_op.drop_index(batch_op.f('ix_services_id'))

    op.drop_table('services')
    with op.batch_alter_table('pricing_packages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pricing_packages_slug'))
        batch_op.drop_index(batch_op.f('ix_pricing_packages_id'))

    op.drop_table('pricing_packages')
    with op.batch_alter_table('portfolio_projects', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_slug'))
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_industry'))
        batch_op.drop_index(batch_op.f('ix_portfolio_projects_id'))

    op.drop_table('portfolio_projects')
    # ### end Alembic commands ###
